export const ALL_PRODUCTS = 'Tous les produits'
export const CATEGORY_LEVEL_0 = 'hierarchicalMenu[categoriesLevel0][0]'
export const CATEGORY_LEVEL_1 = 'hierarchicalMenu[categoriesLevel0][1]'
export const SUPPLIER_REFINEMENT = 'menu[supplier]'
export const HOME = 'Accueil'
